export const BASE_URL = "http://localhost:8000/api";
export const AUTH_PARAMS_LOGIN = "/auth/login";
export const ACCESS_TOKEN_KEY = "accessToken";
export const REFRESH_TOKEN_KEY = "refreshToken";
export const USER_ID = "userId";
export const USER_AUTH_THUNK_KEY = "user/auth";
export const USER_DATA_THUNK_KEY = "user/data";
export const SEARCH_HISTORY = "search_history";
export const MAP_API_TOKEN =
  "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjJhZTdlMTFiOGViMDM5YmNkODM1ZGFkZjllNWRkYWYwYmJlYjhkMmIwNTE5N2E3MjI3NTU3MTQwNjllZDVkMTlhYzBkNDkzOTIxMTQ5NzVmIn0.eyJhdWQiOiIxNjg0NSIsImp0aSI6IjJhZTdlMTFiOGViMDM5YmNkODM1ZGFkZjllNWRkYWYwYmJlYjhkMmIwNTE5N2E3MjI3NTU3MTQwNjllZDVkMTlhYzBkNDkzOTIxMTQ5NzVmIiwiaWF0IjoxNjQzMzc4MTU2LCJuYmYiOjE2NDMzNzgxNTYsImV4cCI6MTY0NTg4Mzc1Niwic3ViIjoiIiwic2NvcGVzIjpbImJhc2ljIl19.UFiBu0md_tejUYQL4nmf6QsoJQXbTJONbNn5GdjtlssptRqYbqtiiYuUdPdvHC4Hn6hdM38VzceCLiCQ-QoYop1Jr5uk2N9Sh4BGf27fHHkoSmZl5v1fz5iMbnThiMoTzdFP1ithcb67EWrFZ6SaEXahYpVjyj7I3Zo3o7tS1AAIc4i1jdNv9I6kYla1uHIJkjDXUQ-kMGUJJ1b-v81Gb5rnRUKmEcA0qZsLGO7hoK4ZjU60gTHUlJdjjgytUSuvRfgvunXsfwu1gw7-t5OWs_B1K-IUtH-EabhF_3IG8QfV2X9S88NQBAm0f1Q93Hl-KhGNFe6Y04MW-Kz5JTceWA";
